### ISSUE TITLE
Help Wanted Redux for 1.6 is causing error item (-75)

### ISSUE THREAD

**Issue by Learyp** [weizinai/StardewValleyMods#1]
https://smapi.io/log/9d23e6b6928c4ff192548a7a7e7776b8

![image_2024-04-14_140227370](https://github.com/weizinai/StardewValleyMods/assets/166973335/8b92db3f-411e-4f6e-bdb8-1ead11f36944)

So it grabbed the category# and thought it was an item code instead.

**Comment by weizinai** [comment]
I have fixed this bug.
